apiVersion: v1
kind: ConfigMap
metadata:
  name: ue1-configmap
  namespace: open5gs
data:
  ue0.conf: {{ .Files.Get "config/ue0.conf" | quote }}
  wrapper.sh: {{ .Files.Get "config/wrapper.sh" | quote }}
  start_ue.sh: {{ .Files.Get "config/start_ue.sh" | quote }}
  start_gnu.sh: {{ .Files.Get "config/start_gnu.sh" | quote }}
  add_route.sh: {{ .Files.Get "config/add_route.sh" | quote }}
  generate_ue_conf.py: {{ .Files.Get "config/generate_ue_conf.py" | quote }}
  multi_ue_scenario.py: {{ .Files.Get "config/multi_ue_scenario.py" | quote }}